apiVersion: apps/v1
kind: Deployment
metadata:
  name: bds-go-auth-api
  labels:
    app: bds-go-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bds-go-auth-api
  template:
    metadata:
      labels:
        app: bds-go-auth-api
    spec:
      containers:
        - name: bds-go-auth-api
          image: bds-go-auth-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bds-go-auth-service
spec:
  selector:
    app: bds-go-auth-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
