apiVersion: apps/v1
kind: Deployment
metadata:
  name: bds-api
  labels:
    app: bds-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bds-api
  template:
    metadata:
      labels:
        app: bds-api
    spec:
      containers:
        - name: bds-api
          image: bds-service
          imagePullPolicy: Never
          ports:
            - containerPort: 2011

---
apiVersion: v1
kind: Service
metadata:
  name: bds-api-service
spec:
  selector:
    app: bds-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2011
      targetPort: 2011
      nodePort: 32011
