apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-storage
              subPath: data
            - mountPath: "/docker-entrypoint-initdb.d"
              name: mysql-storage
              subPath: initdb
            - mountPath: "/etc/mysql/conf.d"
              name: mysql-storage
              subPath: conf
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bds-configmap
                  key: allow_empty_password
            - name: LANG
              valueFrom:
                configMapKeyRef:
                  name: bds-configmap
                  key: mysql_lang

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30311
